### ISSUE TITLE
uninitialized constant Class::UICKeyChainStore

### ISSUE THREAD

**Issue by ronyv89** [IconoclastLabs/motion-keychain#3]
I am getting this error while using motion-keychain

uninitialized constant Class::UICKeyChainStore

**Comment by GantMan** [comment]
You probably need to clean all, then bundle and take pod:install. I have a gem that helps with this (out of sync build process) called newclear.

**Comment by ronyv89** [comment]
Just did. Didn't help

**Comment by GantMan** [comment]
Odd. Can you do a screen share with me, or record the whole clean and build process?

**Comment by GantMan** [comment]
def add my newclear gem and do `rake newclear`  in your project.

**Comment by ronyv89** [comment]
newclear didn't help me. Switched to Lockbox. Sorry

**Comment by GantMan** [comment]
sorry I couldn't help!   Let me know if you'd like to screen share.  I wish you the best!

**Comment by eahanson** [comment]
I had this problem too (in my case, when I upgraded to iOS 9, Xcode 7, and El Capitan). I'm sure there are multiple possible reasons for this error, and therefore multiple possible solutions, but my solution was to explicitly depend on the UICKeyChainStore pod in my Rakefile.
