### ISSUE TITLE
iOS7 -- dyld: Symbol not found: _kSecAttrAccessControl

### ISSUE THREAD

**Issue by zhigang1992** [IconoclastLabs/motion-keychain#4]
```
dyld: Symbol not found: _kSecAttrAccessControl
```

https://github.com/kishikawakatsumi/UICKeyChainStore/issues/80
Seem like it's a problem regarding the pod, but I'm not sure how to fix this rubymotion.
It's this working on your iOS7 devices?

**Comment by GantMan** [comment]
do you have a project I could reference and fix?

**Comment by zhigang1992** [comment]
I'm sorry seems like clean all fixed it, I should have tried this before I send out the issue...
